spring:
  profiles:
    active: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/pofo;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: create

  redis:
    ssl: false
    host: 127.0.0.1
    port: 6379
    password:

app:
  jwt:
    secret: 1qa2ws3ed
    expire: 86400000 # ms