spring:
  profiles:
    active: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/pofo;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: create

  redis:
    ssl: false
    host: 132.226.227.191
    port: 6379
    password:

  servlet:
    multipart:
      max-file-size: 10MB # 파일의 최대 크기 설정
      max-request-size: 50MB # 요청의 최대 크기 설정

app:
  jwt:
    secret: 1qa2ws3ed
    expire: 12 # hour
  file:
    upload:
      path: /upload/local