spring:
  profiles:
    active: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/pofo;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: create